// EmployeeManagementVue.UI/src/pages/EmployeeManagement.vue
<script setup lang="ts">
import { ref, onMounted, computed, watch } from 'vue'
import { useRoute } from 'vue-router'
import { getMyPages } from '@/services/pageService'
import { 
  getEmployees, 
  getCompanies, 
  getRoles,
  addEmployee,
  updateEmployee,
  deleteEmployee,
  type Employee,
  type Company,
  type Role,
  type NewEmployee
} from '@/services/employeeService'

const route = useRoute()

// State
const pageTitle = ref('Employee')
const employees = ref<Employee[]>([])
const companies = ref<Company[]>([])
const roles = ref<Role[]>([])
const loading = ref(true)
const dialog = ref(false)
const deleteDialog = ref(false)
const editingEmployee = ref<Employee | null>(null)
const employeeToDelete = ref<Employee | null>(null)
const page = ref(1)
const itemsPerPage = ref(20)
const error = ref<string | null>(null)
const showError = ref(false)

// Methods
const loadData = async () => {
  if (loading.value && employees.value.length > 0) return // Only prevent reload if we already have data

  try {
    loading.value = true
    const [employeesData, companiesData, rolesData] = await Promise.all([
      getEmployees(),
      getCompanies(),
      getRoles()
    ])
    employees.value = employeesData
    companies.value = companiesData
    roles.value = rolesData
    error.value = null
    showError.value = false
  } catch (err) {
    console.error('Error loading data:', err)
    error.value = 'Failed to load data'
    showError.value = true
    employees.value = []
    companies.value = []
    roles.value = []
  } finally {
    loading.value = false
  }
}

// Watch route changes
watch(
  () => route.path,
  (newPath) => {
    if (newPath === '/employee') {
      loadData()
    }
  },
  { immediate: true }
)

// Computed
const paginatedEmployees = computed(() => {
  const start = (page.value - 1) * itemsPerPage.value
  const end = start + itemsPerPage.value
  return employees.value.slice(start, end)
})

const totalItems = computed(() => employees.value.length)

const totalPages = computed(() => Math.ceil(employees.value.length / itemsPerPage.value))

// Watch page changes
watch([page, itemsPerPage], () => {
  if (page.value > totalPages.value && totalPages.value > 0) {
    page.value = totalPages.value
  }
})

const newEmployee = ref<NewEmployee>({
  personnel: {
    firstName: '',
    lastName: '',
    email: ''
  },
  user: {
    username: '',
    password: '',
    companyId: ''
  },
  role: {
    roleId: ''
  }
})

const loadPageTitle = async () => {
  try {
    const pages = await getMyPages()
    const employeePage = pages.find(page => page.url?.includes('employee'))
    if (employeePage) {
      pageTitle.value = employeePage.pageName
    }
  } catch (err) {
    console.error('Error loading page title:', err)
  }
}

const handleAddEmployee = async () => {
  try {
    await addEmployee(newEmployee.value)
    dialog.value = false
    resetForm()
    await loadData()
    error.value = null
    showError.value = false
  } catch (err) {
    console.error('Error adding employee:', err)
    error.value = 'Failed to add employee'
    showError.value = true
  }
}

const handleEditEmployee = (employee: Employee) => {
  editingEmployee.value = employee
  newEmployee.value = {
    personnel: {
      firstName: employee.firstName,
      lastName: employee.lastName,
      email: employee.email
    },
    user: {
      username: employee.userName,
      password: '', // Leave empty for editing
      companyId: employee.companyId
    },
    role: {
      roleId: employee.roleId
    }
  }
  dialog.value = true
}

const handleUpdateEmployee = async () => {
  if (!editingEmployee.value) return

  try {
    await updateEmployee(editingEmployee.value.personnelId, newEmployee.value)
    dialog.value = false
    resetForm()
    await loadData()
    error.value = null
    showError.value = false
  } catch (err) {
    console.error('Error updating employee:', err)
    error.value = 'Failed to update employee'
    showError.value = true
  }
}

const handleDeleteClick = (employee: Employee) => {
  employeeToDelete.value = employee
  deleteDialog.value = true
}

const handleDeleteConfirm = async () => {
  if (!employeeToDelete.value) return

  try {
    await deleteEmployee(employeeToDelete.value.personnelId)
    deleteDialog.value = false
    employeeToDelete.value = null
    await loadData()
    error.value = null
    showError.value = false
  } catch (err) {
    console.error('Error deleting employee:', err)
    error.value = 'Failed to delete employee'
    showError.value = true
  }
}

const resetForm = () => {
  editingEmployee.value = null
  newEmployee.value = {
    personnel: {
      firstName: '',
      lastName: '',
      email: ''
    },
    user: {
      username: '',
      password: '',
      companyId: ''
    },
    role: {
      roleId: ''
    }
  }
}

const closeDialog = () => {
  dialog.value = false
  resetForm()
}

// Lifecycle hooks
onMounted(() => {
  loadPageTitle()
})
</script>

<template>
  <div class="employee-container">
    <h1 class="text-h4 mb-4">Employee Management</h1>

    <!-- Add Employee Button -->
    <div class="d-flex justify-end mb-4">
      <v-btn
        color="primary"
        prepend-icon="mdi-plus"
        @click="dialog = true"
        :disabled="loading"
        block
      >
        ADD EMPLOYEE
      </v-btn>
    </div>

    <!-- Loading State -->
    <v-row v-if="loading">
      <v-col cols="12" class="d-flex justify-center">
        <v-progress-circular
          indeterminate
          color="primary"
        ></v-progress-circular>
      </v-col>
    </v-row>

    <!-- Error State -->
    <v-row v-else-if="error">
      <v-col cols="12">
        <v-alert
          type="error"
          :text="error"
        ></v-alert>
      </v-col>
    </v-row>

    <!-- Employees Table -->
    <v-row v-else>
      <v-col cols="12">
        <v-card>
          <v-card-text>
            <v-table>
              <thead>
                <tr>
                  <th>Personnel ID</th>
                  <th>First Name</th>
                  <th>Last Name</th>
                  <th>Email</th>
                  <th>Company Name</th>
                  <th>UserName</th>
                  <th>Role Name</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="employee in paginatedEmployees" :key="employee.personnelId">
                  <td>{{ employee.personnelId }}</td>
                  <td>{{ employee.firstName }}</td>
                  <td>{{ employee.lastName }}</td>
                  <td>{{ employee.email }}</td>
                  <td>{{ employee.companyName }}</td>
                  <td>{{ employee.userName }}</td>
                  <td>{{ employee.roleName }}</td>
                  <td>
                    <v-btn
                      icon="mdi-pencil"
                      variant="text"
                      color="primary"
                      density="compact"
                      @click="handleEditEmployee(employee)"
                    />
                    <v-btn
                      icon="mdi-delete"
                      variant="text"
                      color="error"
                      density="compact"
                      @click="handleDeleteClick(employee)"
                    />
                  </td>
                </tr>
              </tbody>
            </v-table>

            <!-- Pagination -->
            <div class="d-flex align-center justify-space-between mt-4 px-2">
              <div class="d-flex align-center">
                <span class="text-caption me-2">Rows per page</span>
                <v-select
                  v-model="itemsPerPage"
                  :items="[10, 20, 50]"
                  variant="plain"
                  density="compact"
                  hide-details
                  class="pagination-select"
                />
              </div>
              <div class="text-caption">
                {{ page }}-{{ Math.min(page * itemsPerPage, employees.length) }} of {{ employees.length }}
              </div>
              <div class="d-flex align-center">
                <v-btn
                  icon="mdi-chevron-left"
                  variant="text"
                  density="compact"
                  :disabled="page === 1"
                  @click="page--"
                />
                <v-btn
                  icon="mdi-chevron-right"
                  variant="text"
                  density="compact"
                  :disabled="page >= totalPages"
                  @click="page++"
                />
              </div>
            </div>
          </v-card-text>
        </v-card>
      </v-col>
    </v-row>

    <!-- Add/Edit Dialog -->
    <v-dialog v-model="dialog" max-width="600px">
      <v-card>
        <v-card-title>
          {{ editingEmployee ? 'Edit Employee' : 'Add Employee' }}
        </v-card-title>
        <v-card-text>
          <v-form @submit.prevent="editingEmployee ? handleUpdateEmployee() : handleAddEmployee()">
            <v-text-field
              v-model="newEmployee.personnel.firstName"
              label="First Name"
              required
            />
            <v-text-field
              v-model="newEmployee.personnel.lastName"
              label="Last Name"
              required
            />
            <v-text-field
              v-model="newEmployee.personnel.email"
              label="Email"
              type="email"
              required
            />
            <v-text-field
              v-model="newEmployee.user.username"
              label="Username"
              required
            />
            <v-text-field
              v-model="newEmployee.user.password"
              label="Password"
              type="password"
              :required="!editingEmployee"
            />
            <v-select
              v-model="newEmployee.user.companyId"
              :items="companies"
              item-title="companyName"
              item-value="companyId"
              label="Company"
              required
            />
            <v-select
              v-model="newEmployee.role.roleId"
              :items="roles"
              item-title="roleName"
              item-value="roleId"
              label="Role"
              required
            />
          </v-form>
        </v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn
            color="grey"
            variant="text"
            @click="closeDialog"
          >
            Cancel
          </v-btn>
          <v-btn
            color="primary"
            @click="editingEmployee ? handleUpdateEmployee() : handleAddEmployee()"
            :loading="loading"
          >
            {{ editingEmployee ? 'Update' : 'Add' }}
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>

    <!-- Delete Confirmation Dialog -->
    <v-dialog v-model="deleteDialog" max-width="400px">
      <v-card>
        <v-card-title>Confirm Delete</v-card-title>
        <v-card-text>
          Are you sure you want to delete this employee?
        </v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn
            color="grey"
            variant="text"
            @click="deleteDialog = false"
          >
            Cancel
          </v-btn>
          <v-btn
            color="error"
            @click="handleDeleteConfirm"
            :loading="loading"
          >
            Delete
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </div>
</template>

<style scoped>
.employee-container {
  padding: 20px;
  background-color: #f5f6fa;
  min-height: 100%;
}

.v-table {
  background-color: white;
}

.v-table th {
  font-weight: 500 !important;
  color: rgba(0, 0, 0, 0.87) !important;
  font-size: 0.875rem !important;
}

.v-table td {
  color: rgba(0, 0, 0, 0.87) !important;
  font-size: 0.875rem !important;
}

.v-btn {
  text-transform: none !important;
}

.pagination-select {
  width: 70px !important;
}

.pagination-select :deep(.v-field__input) {
  padding: 0;
  min-height: 32px;
}

.pagination-select :deep(.v-field) {
  border-radius: 0;
  box-shadow: none;
  background: transparent;
}
</style>

// EmployeeManagementReact.UI/src/pages/EmployeeManagement.tsx
import React, { useEffect, useState } from 'react';
import { getMyPages } from '../services/pageService';
import {
    Table,
    TableBody,
    TableCell,
    TableContainer,
    TableHead,
    TableRow,
    Paper,
    CircularProgress,
    Typography,
    Box,
    Container,
    Stack,
    Button,
    Dialog,
    DialogTitle,
    DialogContent,
    DialogActions,
    TextField,
    Select,
    MenuItem,
    FormControl,
    InputLabel,
    Snackbar,
    Alert,
    IconButton,
    Tooltip,
} from '@mui/material';
import { Add as AddIcon, Edit as EditIcon, Delete as DeleteIcon } from '@mui/icons-material';
import axios from 'axios';
import { jwtDecode } from "jwt-decode";

const getTokenFromCookie = (): string | null => {
    const token = document.cookie
        .split('; ')
        .find(row => row.startsWith('auth_token='))
        ?.split('=')[1];
    return token || null;
};

interface Employee {
    personnelId: string;
    firstName: string;
    lastName: string;
    userName: string;
    email: string;
    companyId: string;
    companyName: string;
    roleId: string;
    roleName: string;
}

interface DecodedToken {
    CompanyId: string;
    // Add other token claims if needed
}

interface Company {
    companyId: string;
    companyName: string;
}

interface Role {
    roleId: string;
    roleName: string;
}

interface NewEmployee {
    personnel: {
        firstName: string;
        lastName: string;
        email: string;
    };
    user: {
        username: string;
        password: string;
        companyId: string;
    };
    role: {
        roleId: string;
    };
}

const EmployeeManagement: React.FC = () => {
    const [pageTitle, setPageTitle] = useState('Employee');
    const [employees, setEmployees] = useState<Employee[]>([]);
    const [loading, setLoading] = useState(true);
    const [openDialog, setOpenDialog] = useState(false);
    const [companies, setCompanies] = useState<Company[]>([]);
    const [roles, setRoles] = useState<Role[]>([]);
    const [editingEmployee, setEditingEmployee] = useState<Employee | null>(null);
    const [newEmployee, setNewEmployee] = useState<NewEmployee>({
        personnel: {
            firstName: '',
            lastName: '',
            email: '',
        },
        user: {
            username: '',
            password: '',
            companyId: '',
        },
        role: {
            roleId: '',
        },
    });
    const [snackbar, setSnackbar] = useState({
        open: false,
        message: '',
        severity: 'success' as 'success' | 'error' | 'info'
    });
    const [deleteConfirmOpen, setDeleteConfirmOpen] = useState(false);
    const [employeeToDelete, setEmployeeToDelete] = useState<Employee | null>(null);

    const fetchEmployees = async () => {
        try {
            const token = getTokenFromCookie();
            if (!token) {
                throw new Error('No authentication token found');
            }

            // Decode token to get companyId
            const decodedToken = jwtDecode<DecodedToken>(token);
            const companyId = decodedToken.CompanyId;

            const response = await axios.get(`https://localhost:7076/api/v1/company/${companyId}/employee`, {
                headers: {
                    'Authorization': `Bearer ${token}`
                }
            });
            setEmployees(response.data);
            setLoading(false);
        } catch (error) {
            console.error('Error fetching employees:', error);
            setLoading(false);
        }
    };

    const fetchCompanies = async () => {
        try {
            const token = getTokenFromCookie();
            if (!token) {
                throw new Error('No authentication token found');
            }

            const response = await axios.get('https://localhost:7076/api/v1/company/get-companies', {
                headers: {
                    'Authorization': `Bearer ${token}`
                }
            });
            setCompanies(response.data);
        } catch (error) {
            console.error('Error fetching companies:', error);
            setSnackbar({
                open: true,
                message: 'Error fetching companies',
                severity: 'error'
            });
        }
    };

    const fetchRoles = async () => {
        try {
            const token = getTokenFromCookie();
            if (!token) {
                throw new Error('No authentication token found');
            }
            const decodedToken = jwtDecode<DecodedToken>(token);
            const companyId = decodedToken.CompanyId;
            const response = await axios.get(`https://localhost:7076/api/v1/company/${companyId}/roles`, {
                headers: {
                    'Authorization': `Bearer ${token}`
                }
            });
            setRoles(response.data);
        } catch (error) {
            console.error('Error fetching roles:', error);
            setSnackbar({
                open: true,
                message: 'Error fetching roles',
                severity: 'error'
            });
        }
    };

    const handleAddEmployee = async () => {
        try {
            const token = getTokenFromCookie();
            if (!token) {
                throw new Error('No authentication token found');
            }

            const decodedToken = jwtDecode<DecodedToken>(token);
            const companyId = decodedToken.CompanyId;
            await axios.post(
                `https://localhost:7076/api/v1/company/${companyId}/employee`,
                newEmployee,
                {
                    headers: {
                        'Authorization': `Bearer ${token}`,
                        'Content-Type': 'application/json'
                    }
                }
            );

            setSnackbar({
                open: true,
                message: 'Employee added successfully',
                severity: 'success'
            });
            setOpenDialog(false);
            resetNewEmployee();
            fetchEmployees();
        } catch (error) {
            console.error('Error adding employee:', error);
            setSnackbar({
                open: true,
                message: 'Error adding employee',
                severity: 'error'
            });
        }
    };

    const handleEditEmployee = async (employee: Employee) => {
        // First load companies and roles
        await Promise.all([fetchCompanies(), fetchRoles()]);
        
        setEditingEmployee(employee);
        setNewEmployee({
            personnel: {
                firstName: employee.firstName,
                lastName: employee.lastName,
                email: employee.email,
            },
            user: {
                username: employee.userName,
                password: '', // Leave empty for editing
                companyId: employee.companyId, // Use companyId instead of userCompanyId
            },
            role: {
                roleId: employee.roleId,
            },
        });
        setOpenDialog(true);
    };

    const handleUpdateEmployee = async () => {
        try {
            const token = getTokenFromCookie();
            if (!token || !editingEmployee) {
                throw new Error('No authentication token found or no employee selected');
            }

            const decodedToken = jwtDecode<DecodedToken>(token);
            const companyId = decodedToken.CompanyId;

            await axios.put(
                `https://localhost:7076/api/v1/company/${companyId}/employee/${editingEmployee.personnelId}`,
                newEmployee,
                {
                    headers: {
                        'Authorization': `Bearer ${token}`,
                        'Content-Type': 'application/json'
                    }
                }
            );

            setSnackbar({
                open: true,
                message: 'Employee updated successfully',
                severity: 'success'
            });
            setOpenDialog(false);
            resetNewEmployee();
            setEditingEmployee(null);
            fetchEmployees();
        } catch (error) {
            console.error('Error updating employee:', error);
            setSnackbar({
                open: true,
                message: 'Error updating employee',
                severity: 'error'
            });
        }
    };

    const resetNewEmployee = () => {
        setNewEmployee({
            personnel: {
                firstName: '',
                lastName: '',
                email: '',
            },
            user: {
                username: '',
                password: '',
                companyId: '',
            },
            role: {
                roleId: '',
            },
        });
    };

    const handleCloseDialog = () => {
        setOpenDialog(false);
        resetNewEmployee();
        setEditingEmployee(null);
    };

    const handleCloseSnackbar = () => {
        setSnackbar({ ...snackbar, open: false });
    };

    const handleDeleteClick = (employee: Employee) => {
        setEmployeeToDelete(employee);
        setDeleteConfirmOpen(true);
    };

    const handleDeleteConfirm = async () => {
        try {
            const token = getTokenFromCookie();
            if (!token || !employeeToDelete) {
                throw new Error('No authentication token found or no employee selected');
            }

            const decodedToken = jwtDecode<DecodedToken>(token);
            const companyId = decodedToken.CompanyId;

            await axios.delete(
                `https://localhost:7076/api/v1/company/${companyId}/employee/${employeeToDelete.personnelId}`,
                {
                    headers: {
                        'Authorization': `Bearer ${token}`
                    }
                }
            );

            setSnackbar({
                open: true,
                message: 'Employee deleted successfully',
                severity: 'success'
            });
            setDeleteConfirmOpen(false);
            setEmployeeToDelete(null);
            fetchEmployees();
        } catch (error) {
            console.error('Error deleting employee:', error);
            setSnackbar({
                open: true,
                message: 'Error deleting employee',
                severity: 'error'
            });
        }
    };

    const handleDeleteCancel = () => {
        setDeleteConfirmOpen(false);
        setEmployeeToDelete(null);
    };

    useEffect(() => {
        const fetchPageTitle = async () => {
            try {
                const pages = await getMyPages();
                const employeePage = pages.find(page => page.url?.includes('employee'));
                if (employeePage) {
                    setPageTitle(employeePage.pageName);
                }
            } catch (error) {
                console.error('Error fetching page title:', error);
            }
        };

        fetchPageTitle();
        fetchEmployees();
    }, []);

    // Load companies and roles when dialog opens for adding new employee
    useEffect(() => {
        if (openDialog && !editingEmployee) {
            Promise.all([fetchCompanies(), fetchRoles()]);
        }
    }, [openDialog]);

    return (
        <Stack spacing={3}>
            <Box sx={{ 
                borderBottom: '1px solid #e0e0e0',
                pb: 2,
                display: 'flex',
                alignItems: 'center'
            }}>
                <Typography 
                    variant="h4" 
                    component="h1" 
                    sx={{ 
                        color: '#666',
                        fontWeight: 500,
                        fontSize: '1.75rem'
                    }}
                >
                    {pageTitle}
                </Typography>
                <Typography 
                    variant="h4" 
                    component="span" 
                    sx={{ 
                        color: '#666',
                        fontWeight: 400,
                        fontSize: '1.75rem',
                        ml: 1
                    }}
                >
                    Management
                </Typography>
            </Box>

            <Container maxWidth={false} sx={{ p: 0 }}>
                <Box sx={{ mb: 2 }}>
                    <Button
                        variant="contained"
                        color="primary"
                        startIcon={<AddIcon />}
                        onClick={() => setOpenDialog(true)}
                        fullWidth
                        sx={{ 
                            borderRadius: 1,
                            py: 1.5,
                            backgroundColor: '#1976d2',
                            '&:hover': {
                                backgroundColor: '#1565c0'
                            }
                        }}
                    >
                        ADD EMPLOYEE
                    </Button>
                </Box>

                {loading ? (
                    <Box sx={{ display: 'flex', justifyContent: 'center', p: 4 }}>
                        <CircularProgress />
                    </Box>
                ) : (
                    <Paper sx={{ borderRadius: 1, overflow: 'hidden' }}>
                        <Table>
                            <TableHead>
                                <TableRow>
                                    <TableCell sx={{ 
                                        fontWeight: 500,
                                        backgroundColor: '#fff',
                                        borderBottom: '1px solid #e0e0e0'
                                    }}>
                                        Personnel ID
                                    </TableCell>
                                    <TableCell sx={{ 
                                        fontWeight: 500,
                                        backgroundColor: '#fff',
                                        borderBottom: '1px solid #e0e0e0'
                                    }}>
                                        First Name
                                    </TableCell>
                                    <TableCell sx={{ 
                                        fontWeight: 500,
                                        backgroundColor: '#fff',
                                        borderBottom: '1px solid #e0e0e0'
                                    }}>
                                        Last Name
                                    </TableCell>
                                    <TableCell sx={{ 
                                        fontWeight: 500,
                                        backgroundColor: '#fff',
                                        borderBottom: '1px solid #e0e0e0'
                                    }}>
                                        Email
                                    </TableCell>
                                    <TableCell sx={{ 
                                        fontWeight: 500,
                                        backgroundColor: '#fff',
                                        borderBottom: '1px solid #e0e0e0'
                                    }}>
                                        Company Name
                                    </TableCell>
                                    <TableCell sx={{ 
                                        fontWeight: 500,
                                        backgroundColor: '#fff',
                                        borderBottom: '1px solid #e0e0e0'
                                    }}>
                                        UserName
                                    </TableCell>
                                    <TableCell sx={{ 
                                        fontWeight: 500,
                                        backgroundColor: '#fff',
                                        borderBottom: '1px solid #e0e0e0'
                                    }}>
                                        Role Name
                                    </TableCell>
                                    <TableCell sx={{ 
                                        fontWeight: 500,
                                        backgroundColor: '#fff',
                                        borderBottom: '1px solid #e0e0e0',
                                        width: '80px'
                                    }}>
                                        Actions
                                    </TableCell>
                                </TableRow>
                            </TableHead>
                            <TableBody>
                                {employees.map((employee) => (
                                    <TableRow 
                                        key={employee.personnelId} 
                                        hover
                                        sx={{
                                            '&:last-child td': { borderBottom: 0 }
                                        }}
                                    >
                                        <TableCell sx={{ color: 'text.secondary' }}>
                                            {employee.personnelId}
                                        </TableCell>
                                        <TableCell>{employee.firstName}</TableCell>
                                        <TableCell>{employee.lastName}</TableCell>
                                        <TableCell>{employee.email}</TableCell>
                                        <TableCell>{employee.companyName}</TableCell>
                                        <TableCell>{employee.userName}</TableCell>
                                        <TableCell>{employee.roleName}</TableCell>
                                        <TableCell>
                                            <Tooltip title="Edit employee">
                                                <IconButton
                                                    color="info"
                                                    onClick={() => handleEditEmployee(employee)}
                                                    size="small"
                                                    sx={{ mr: 1 }}
                                                >
                                                    <EditIcon fontSize="small" />
                                                </IconButton>
                                            </Tooltip>
                                            <Tooltip title="Delete employee">
                                                <IconButton
                                                    color="error"
                                                    onClick={() => handleDeleteClick(employee)}
                                                    size="small"
                                                >
                                                    <DeleteIcon fontSize="small" />
                                                </IconButton>
                                            </Tooltip>
                                        </TableCell>
                                    </TableRow>
                                ))}
                            </TableBody>
                        </Table>
                    </Paper>
                )}

                <Dialog 
                    open={openDialog} 
                    onClose={handleCloseDialog}
                    PaperProps={{
                        sx: { borderRadius: 1, width: '500px' }
                    }}
                >
                    <DialogTitle sx={{ pb: 2, borderBottom: '1px solid #e0e0e0' }}>
                        {editingEmployee ? 'Edit Employee' : 'Add New Employee'}
                    </DialogTitle>
                    <DialogContent sx={{ mt: 2 }}>
                        <Stack spacing={2}>
                            <TextField
                                label="First Name"
                                fullWidth
                                value={newEmployee.personnel.firstName}
                                onChange={(e) => setNewEmployee(prev => ({
                                    ...prev,
                                    personnel: {
                                        ...prev.personnel,
                                        firstName: e.target.value
                                    }
                                }))}
                                variant="outlined"
                            />
                            <TextField
                                label="Last Name"
                                fullWidth
                                value={newEmployee.personnel.lastName}
                                onChange={(e) => setNewEmployee(prev => ({
                                    ...prev,
                                    personnel: {
                                        ...prev.personnel,
                                        lastName: e.target.value
                                    }
                                }))}
                                variant="outlined"
                            />
                            <TextField
                                label="Email"
                                type="email"
                                fullWidth
                                value={newEmployee.personnel.email}
                                onChange={(e) => setNewEmployee(prev => ({
                                    ...prev,
                                    personnel: {
                                        ...prev.personnel,
                                        email: e.target.value
                                    }
                                }))}
                                variant="outlined"
                            />
                            <TextField
                                label="Username"
                                fullWidth
                                value={newEmployee.user.username}
                                onChange={(e) => setNewEmployee(prev => ({
                                    ...prev,
                                    user: {
                                        ...prev.user,
                                        username: e.target.value
                                    }
                                }))}
                                variant="outlined"
                            />
                            <TextField
                                label="Password"
                                type="password"
                                fullWidth
                                value={newEmployee.user.password}
                                onChange={(e) => setNewEmployee(prev => ({
                                    ...prev,
                                    user: {
                                        ...prev.user,
                                        password: e.target.value
                                    }
                                }))}
                                helperText={editingEmployee ? "Leave empty to keep current password" : ""}
                                variant="outlined"
                            />
                            <FormControl fullWidth variant="outlined">
                                <InputLabel>Company</InputLabel>
                                <Select
                                    value={newEmployee.user.companyId}
                                    label="Company"
                                    onChange={(e) => setNewEmployee(prev => ({
                                        ...prev,
                                        user: {
                                            ...prev.user,
                                            companyId: e.target.value
                                        }
                                    }))}
                                >
                                    {companies.map((company) => (
                                        <MenuItem key={company.companyId} value={company.companyId}>
                                            {company.companyName}
                                        </MenuItem>
                                    ))}
                                </Select>
                            </FormControl>
                            <FormControl fullWidth variant="outlined">
                                <InputLabel>Role</InputLabel>
                                <Select
                                    value={newEmployee.role.roleId}
                                    label="Role"
                                    onChange={(e) => setNewEmployee(prev => ({
                                        ...prev,
                                        role: {
                                            roleId: e.target.value
                                        }
                                    }))}
                                >
                                    {roles.map((role) => (
                                        <MenuItem key={role.roleId} value={role.roleId}>
                                            {role.roleName}
                                        </MenuItem>
                                    ))}
                                </Select>
                            </FormControl>
                        </Stack>
                    </DialogContent>
                    <DialogActions sx={{ p: 2, pt: 1 }}>
                        <Button onClick={handleCloseDialog} color="inherit">
                            Cancel
                        </Button>
                        <Button 
                            onClick={editingEmployee ? handleUpdateEmployee : handleAddEmployee}
                            variant="contained"
                            disabled={
                                !newEmployee.personnel.firstName ||
                                !newEmployee.personnel.lastName ||
                                !newEmployee.personnel.email ||
                                !newEmployee.user.username ||
                                (!editingEmployee && !newEmployee.user.password) || // Only require password for new employees
                                !newEmployee.role.roleId
                            }
                        >
                            {editingEmployee ? 'Update' : 'Add'}
                        </Button>
                    </DialogActions>
                </Dialog>

                <Dialog
                    open={deleteConfirmOpen}
                    onClose={handleDeleteCancel}
                    PaperProps={{
                        sx: { borderRadius: 1 }
                    }}
                >
                    <DialogTitle sx={{ pb: 2, borderBottom: '1px solid #e0e0e0' }}>
                        Confirm Delete
                    </DialogTitle>
                    <DialogContent sx={{ mt: 2 }}>
                        <Typography>
                            Are you sure you want to delete employee{' '}
                            <strong>
                                {employeeToDelete?.firstName} {employeeToDelete?.lastName}
                            </strong>
                            ?
                        </Typography>
                    </DialogContent>
                    <DialogActions sx={{ p: 2, pt: 1 }}>
                        <Button onClick={handleDeleteCancel} color="inherit">
                            Cancel
                        </Button>
                        <Button 
                            onClick={handleDeleteConfirm}
                            variant="contained"
                            color="error"
                        >
                            Delete
                        </Button>
                    </DialogActions>
                </Dialog>

                <Snackbar
                    open={snackbar.open}
                    autoHideDuration={6000}
                    onClose={handleCloseSnackbar}
                    anchorOrigin={{ vertical: 'bottom', horizontal: 'right' }}
                >
                    <Alert
                        onClose={handleCloseSnackbar}
                        severity={snackbar.severity}
                        variant="filled"
                        sx={{ width: '100%' }}
                    >
                        {snackbar.message}
                    </Alert>
                </Snackbar>
            </Container>
        </Stack>
    );
};

export default EmployeeManagement;
